/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'configureDomain' : IDL.Func([IDL.Text], [], []),
  'getDomain' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSubdomain' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'isPublished' : IDL.Func([], [IDL.Bool], ['query']),
  'publish' : IDL.Func([IDL.Text], [], []),
  'resetSiteStorage' : IDL.Func([], [], []),
  'unpublish' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'configureDomain' : IDL.Func([IDL.Text], [], []),
    'getDomain' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getSubdomain' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'isPublished' : IDL.Func([], [IDL.Bool], ['query']),
    'publish' : IDL.Func([IDL.Text], [], []),
    'resetSiteStorage' : IDL.Func([], [], []),
    'unpublish' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };